language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greetings

node_js:  
  - "8.9.4"

before_script:
  - psql -c 'create database  greetings;' -U postgres
  - psql -U postgres -d greetings -a -f greet.sql

addons:
  apt:
  packages:
  - postgresql-server-dev-9.2